SELECT * FROM pessoa;

SELECT * FROM instrumento;

CREATE TABLE pessoa(
email VARCHAR(30) PRIMARY KEY UNIQUE,
nome VARCHAR(30) NOT NULL,
sobrenome VARCHAR(30) NOT NULL,
senha VARCHAR(30) NOT NULL);

CREATE TABLE instrumento(
id INTEGER PRIMARY KEY UNIQUE,
tipo VARCHAR(20) NOT NULL,
descricao VARCHAR(30) NOT NULL,
preco NUMERIC(8,2) NOT NULL);

CREATE SEQUENCE usersequence
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1;

ALTER TABLE instrumento ALTER COLUMN id SET DEFAULT NEXTVAL('usersequence'::regclass);

